import type { MockProfile, Topic, ProfileCategory } from './types';
export const topics: Topic[]=['Identity and life situation','Relationship intent','Values and worldview','Communication style','Conflict and repair style','Emotional regulation','Family and children','Lifestyle and daily routine','Work and money','Health, sleep, fitness, and substances','Sex, affection, boundaries, and intimacy','Attraction and aesthetic preferences','Dealbreakers and hard requirements','Growth, accountability, and self-awareness','Natural conversation interests'].map((name,i)=>({name,coverage:[82,76,88,91,54,49,65,58,42,36,31,44,70,62,57][i],confidence:(i<4?'high':i<10?'medium':'low') as any,unresolved:[0,1,0,0,3,3,2,2,4,5,5,3,1,2,2][i],required:i<13}));
export const categories: ProfileCategory[]=[
{id:'intent',categoryName:'Relationship intent',summary:'Seeking a serious long-term relationship with depth before attachment, not casual attention-based app behavior.',observedTraits:['serious intent','dislikes swipe culture','wants compatibility before overinvestment'],evidenceSnippets:['Prefers evidence-guided matching over months of accidental incompatibility discovery.'],confidenceLevel:'medium',importanceLevel:'major',matchLogic:'similarity_needed',observations:[{trait:'Serious relationship focus',evidence:'Stated that long-term fit matters more than volume of introductions.',sourceType:'conversation',confidence:'medium',userConfirmed:null}],openQuestions:['Is marriage required or optional?','What timeline is acceptable?']},
{id:'communication',categoryName:'Communication style',summary:'Direct, accuracy-oriented communication that can sound intense even when not upset.',observedTraits:['direct language','prefers accuracy over reassurance','needs partner to not confuse intensity with hostility'],evidenceSnippets:['Asked the system to preserve exact wording on important subjects.'],confidenceLevel:'high',importanceLevel:'major',matchLogic:'difference_tolerated',observations:[{trait:'Direct communicator',evidence:'Repeatedly chooses precise language over tone-polishing.',sourceType:'conversation',confidence:'high',userConfirmed:true}],openQuestions:['What kind of directness from a partner feels disrespectful?']},
{id:'values',categoryName:'Values and worldview',summary:'High value on honesty, loyalty, responsibility, practical usefulness, and claims that can be verified.',observedTraits:['truth-seeking','low tolerance for performative interaction','accountability-oriented'],evidenceSnippets:['Dishonesty is treated as a hard conflict rather than a preference mismatch.'],confidenceLevel:'high',importanceLevel:'required',matchLogic:'similarity_needed',observations:[{trait:'Honesty as hard gate',evidence:'User rejects fake interaction and hidden unavailability.',sourceType:'conversation',confidence:'high',userConfirmed:true}],openQuestions:['Which values are flexible versus required?']},
{id:'attraction',categoryName:'Attraction and aesthetic preferences',summary:'Attraction matters as a structured compatibility category, but should not dominate trust, values, or hard requirements.',observedTraits:['wants structured attraction model','uses public examples to infer patterns','rejects attraction-first matching'],evidenceSnippets:['Asked for attraction to contribute to a floor, not overpower compatibility.'],confidenceLevel:'medium',importanceLevel:'moderate',matchLogic:'difference_tolerated',observations:[{trait:'Attraction floor, not ranking ladder',evidence:'Attraction should be one category among many.',sourceType:'conversation',confidence:'medium',userConfirmed:null}],openQuestions:['What traits are genuinely important versus flexible?']}
];
export const seedProfile: MockProfile={user:{id:'seed-001',preferredName:'Alex',age:34,relationshipStatus:'single / available declared',relationshipIntent:'serious long-term, marriage-oriented',locationCity:'Austin',locationState:'TX',relocationWillingness:'open for exceptional fit',verificationStatus:'identity pending',trustStatus:'availability declared'},topics,categories,hardGates:[],riskFlags:['verification pending','low intimacy-boundary coverage','conflict repair needs more evidence'],attractionFloor:72,profileConfidence:68,poolProbability:46,relationshipStructure:'exclusive_monogamous',relationshipIntentCategory:'marriage_or_life_commitment',currentAvailabilityStatus:'single',matchingConsent:true};
export const adminUsers: MockProfile[]=[seedProfile,{...seedProfile,user:{...seedProfile.user,id:'seed-002',preferredName:'Morgan',locationCity:'Denver',locationState:'CO',verificationStatus:'identity verified',trustStatus:'trust review complete'},profileConfidence:81,poolProbability:61,riskFlags:['local pool limited'],relationshipStructure:'exclusive_monogamous',relationshipIntentCategory:'serious_long_term',currentAvailabilityStatus:'divorced',matchingConsent:true}];
